### ISSUE TITLE
Version 1.2.1 crashes on 1.14.4

### ISSUE THREAD

**Issue by nonchip** [CottonMC/FunctionAPI#10]
got this one: https://www.curseforge.com/minecraft/mc-mods/function-api/files/2808468 which claims to be for MC1.14.4, but it crashes with:
```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 10/18/19 11:02 AM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/item/ItemStack
	at io.github.cottonmc.jankson.JanksonFactory.builder(JanksonFactory.java:10)
	at io.github.cottonmc.jankson.JanksonFactory.createJankson(JanksonFactory.java:25)
	at io.github.cottonmc.libcd.LibCD.<clinit>(LibCD.java:38)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:198)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.item.ItemStack
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
```
full report attached: 
[crash-2019-10-18_11.02.32-client.txt](https://github.com/CottonMC/FunctionAPI/files/3743115/crash-2019-10-18_11.02.32-client.txt)

a quick google search seems to suggest that `net/minecraft/item/ItemStack` was deprecated/removed since MC1.13?

**Comment by LemmaEOF** [comment]
It hasn't been deprecated or removed. This is an issue with Minecraft being obfuscated; all the names of all the classes and methods and fields are scrambled each release. For some reason, it's trying to look for the deobfuscated name.

Also, this seems to be coming from LibCD, not Function API.

**Comment by nonchip** [comment]
well since i don't have anything called libcd installed, and the issue goes away if i disable function api, i think you might have included that as a packaged dependency? maybe you accidentally built against the deobfuscated library you used for testing or something?

**Comment by LemmaEOF** [comment]
I might have an idea of what's going on. What's your mod list?

**Comment by Frontrider** [comment]
Move to libcd, I'm closing this. ;)

https://github.com/cottonmc/LibCD

**Comment by Frontrider** [comment]
Found it. In an earlier version when I was jijing cotton datapack, that required jankson, that in turn required libcd Jankson was still included.

Building a fixed jar now.

**Comment by nonchip** [comment]
> I might have an idea of what's going on. What's your mod list?

not sure if that's still relevant, but the mod list is in the attachment above, i figured the whole dump would fit there better than just pasting it

**Comment by Frontrider** [comment]
try the new one.

**Comment by nonchip** [comment]
works fine :)
